### ISSUE TITLE
App crashes initial sign in

### ISSUE THREAD

**Issue by Bridouz** [tsangiotis/JekyllForAndroid#36]
The app crashes when we first sign in. No matter if we clear data, cache and reboot

**Comment by micahbolen** [comment]
I was considering using this app, but I noticed it was pulled from the Play Store and I'm getting the same crash.  I wonder if there is a more well-maintained project or if this project is still in active development and just needs some more help from other developers.  I have already forked the repo and am willing to contribute if someone wants to assign me a task.  Otherwise, I will keep looking for an alternative and/or try to figure out a quick fix for this crash problem.

**Comment by tsagi** [comment]
Hi, I stopped maintaining the app due to lack of time and the fact that I stopped using Jekyll to blog. You can fix the problem if you want and I can help however I can. There are also a lot of unfinished changes in the develop branch that are destined to make the app faster and better if you are intersted.

As for screenshots, I don't have any available right now but the app is simple and uses material design according to Google's design guidelines.
